[package]
name        = "tauri-app"
version     = "2.6.0"
description = "A Tauri App"
authors     = ["you"]
edition     = "2021"
repository  = "https://github.com/Uninen/tauri-vue-template"

[lib]
name         = "tauri_app_lib"
crate-type   = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri                        = { version = "2", features = [] }
tauri-plugin-shell           = "2"
tauri-plugin-prevent-default = "2.1"
tauri-plugin-dialog          = "2.3.2"
tauri-plugin-fs              = "2.4.1"

zip = "2.0"       # 处理 zip 解压
chrono    = "0.4"

serde     = { version = "1.0", features = ["derive"] }
serde_json= "1.0"
sha2 = "0.10"     # 计算文件哈希
hex = "0.4"       # 将哈希转为字符串

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
panic         = "abort"
strip         = true
