[package]
name        = "wotb-mod-manager"
version     = "1.0.2"
description = "A Windows mod manager for World of Tanks Blitz"
authors     = ["PWTF-ASF"]
edition     = "2021"
license     = "MIT"
repository  = "https://github.com/PWTF-ASF/WOTB-MOD-Manager"

[lib]
name         = "tauri_app_lib"
crate-type   = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3", features = [] }

[dependencies]
tauri                        = { version = "2.3", features = ["protocol-asset"] }
tauri-plugin-dialog          = "2.3"

zip = "2.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
hex = "0.4"
uuid = { version = "1", features = ["v4"] }
base64 = "0.21"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
panic         = "abort"
strip         = true
