/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abc: typeof import('./src/components/abc.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    Personalize: typeof import('./src/components/Personalize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./src/components/SettingItem.vue')['default']
  }
}
