/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
<<<<<<< HEAD
=======
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
>>>>>>> 016d1dd (初始样式)
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
  }
}
