name: "Release"

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
    steps:
      - uses: actions/checkout@v4

      - id: create-release
        uses: taiki-e/create-gh-release-action@v1
        with:
          title: ${{ github.ref_name }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "26.2.0"

      - uses: pnpm/action-setup@v4
        with:
          version: "10.33.4"

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          releaseBody: "无"
          releaseDraft: true
          args: --target x86_64-pc-windows-msvc --bundles nsis
